FROM node:20-slim

USER root
RUN apt-get update && apt-get install -y \
  python3 make g++ curl gnupg && apt-get clean

RUN mkdir -p /home/user/.cache && chown -R 1000:1000 /home/user/.cache

#USER user
WORKDIR /app

EXPOSE 5173

# start bash
CMD ["bash"]